[build]
  command = "node ./scripts/setup-env.js && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Use Netlify's built-in API proxy pattern instead of serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  # Use more efficient bundling
  node_bundler = "esbuild"
  # Only include truly necessary files - explicitly list the minimal files needed
  included_files = [".env", ".env.production", ".env.local", ".env.production.local"]
  # Keep key external modules external (not bundled)
  external_node_modules = ["mongodb"]

# Configure specific functions with different settings
[functions.api]
  external_node_modules = ["@netlify/functions", "@netlify/next"]

[functions.next_server]
  external_node_modules = ["next", "react", "react-dom"]

[functions.hello]
  included_files = []

[functions.mongodb-connection]
  external_node_modules = ["mongodb"]

[dev]
  framework = "next"
  targetPort = 3000

# Enable compression for HTML
[build.processing.html]
  pretty_urls = true

# Enable CORS for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200 