[build]
  command = "node ./scripts/setup-env.js && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect function for server-side rendered pages
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = false

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/mongodb/**"]
  external_node_modules = ["mongodb", "@netlify/next", "@netlify/functions"]
  
[dev]
  framework = "next"
  targetPort = 3000

# Netlify uses Edge Functions to improve performance
[build.processing.html]
  pretty_urls = true

# Enable CORS for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 