[build]
  command = "node ./scripts/setup-env.js && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Use Netlify's built-in API proxy pattern instead of serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  # Use more efficient bundling
  node_bundler = "esbuild"
  # Only include truly necessary files
  included_files = []
  # Keep key external modules external (not bundled)
  external_node_modules = ["mongodb", "@netlify/next", "@netlify/functions"]

[dev]
  framework = "next"
  targetPort = 3000

# Enable compression for HTML
[build.processing.html]
  pretty_urls = true

# Enable CORS for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization" 